### ISSUE TITLE
Overflowing issue

### ISSUE THREAD

**Issue by gerchprung** [manticorp/unrealheightmap#1]
Hello! Thanks again for this app. Unfortunately, take place the issue with the overflowing. Kindly please find attached screenshot. This issue appear in case, when I want to take high map of the whole world with the polar areas. I know about max size of heightmap in code (300000 px), and input a value in this border, like on the attached screenshot. If I take another region, near equator for instance, this issue can appear, but I can press (one or several times) "generate" button once again and it lead to success. 
I would like to say that app is beautiful already now, despite of this issue.    
![screenshot1](https://user-images.githubusercontent.com/114004168/221905893-aaba69d3-b59d-4728-bb97-a49d8486ea24.jpg)

**Comment by manticorp** [comment]
Aha - this should be fixed as of v0.1.3

https://github.com/manticorp/unrealheightmap/commit/22be4a010a2ce968fd175627886e151627c83a27

https://github.com/manticorp/unrealheightmap/releases/tag/v0.1.3

https://github.com/manticorp/unrealheightmap/tree/v0.1.3
