### ISSUE TITLE
Question(s) about the heightmap information after generating a heightmap

### ISSUE THREAD

**Issue by TheBango** [manticorp/unrealheightmap#10]
![image](https://user-images.githubusercontent.com/37959818/236187893-92b89b71-3896-4e93-b72a-b7ad23fe9e19.png)

As seen in the picture, after generating a heightmap we get some information about which values we should use inside UE5 to get a 1:1 map scale.

1. Do we just have to type in the suggested values in the corresponding fields or do we have to multiply the original scale values by the suggested values?

2. Could you add a button so the user can save those information as a text file?
Or maybe this file could be included with downloading the heightmap.

**Comment by manticorp** [comment]
> 1. Do we just have to type in the suggested values in the corresponding fields or do we have to multiply the original scale values by the suggested values?

Those values should be entered into the fields as-is - i.e. x and y scales should read 305.35 and z scale should read 3.38

> 2. Could you add a button so the user can save those information as a text file? Or maybe this file could be included with downloading the heightmap.

I could make it so that clicking on the number copies it to the clipboard? I don't really see the advantage offered by being able to download these numbers as a file?

p.s. where were you looking at? The height range is 131,391m to 148,672m? or is that actually a decimal?

**Comment by TheBango** [comment]
> I could make it so that clicking on the number copies it to the clipboard? I don't really see the advantage offered by being able to download these numbers as a file?

Well sure, being able to copy the values to the clipboard would work. Actually, the user currently can also copy every info he needs to a file by himself. 

> p.s. where were you looking at? The height range is 131,391m to 148,672m? or is that actually a decimal?

Hmm, regarding this I'm confused now 😅
I would agree since we use a comma as decimal separator in Europe, but I guess you don't use the European standard for this. 
However, since you're using a point as decimal separator for the area size and the m/px resolution (see below picture) I think the height values should also be separated by a point.

![image](https://github.com/manticorp/unrealheightmap/assets/37959818/ef315ba9-3548-4130-a528-1f7e2b6d30e5)

**Comment by manticorp** [comment]
This should be fixed now.
