### ISSUE TITLE
Problems generating Albedo

### ISSUE THREAD

**Issue by FranBare** [manticorp/unrealheightmap#12]
Hi, I am having issues downloading albedo. When the button is clicked, it goes extremely fast through all 1055/1056 and then it gets stuck indefinitely. 
I have checked the console and these are the errors I noticed:

app.ts:944 TypeError: Cannot read properties of undefined (reading 'url')
    at app.ts:935:28
    at new Promise (<anonymous>)
    at _loop_1 (app.ts:918:23)
    at App.<anonymous> (app.ts:908:52)
    at step (zstream.js:47:1)
    at Object.next (zstream.js:47:1)
    at zstream.js:47:1
    at new Promise (<anonymous>)
    at __awaiter (zstream.js:47:1)
    at App.combineImagesSimple (app.ts:878:82)
(anonymous) @ app.ts:944

![image](https://github.com/manticorp/unrealheightmap/assets/154326662/07556652-761a-4b01-ab27-cbdf6728099e)

![image](https://github.com/manticorp/unrealheightmap/assets/154326662/f728724d-dd93-4ff1-992c-fd6cbe595a76)

Thank You for the app and the work you put into it, the heightmap works really well and has helped me a great deal!

Kind regards,
Fran B

**Comment by manticorp** [comment]
This may have been fixed in an update pushed today :) Care to give it a try?
