### ISSUE TITLE
Gaps in landscape tiling

### ISSUE THREAD

**Issue by dvogt2** [manticorp/unrealheightmap#13]
Every time i import a heightmap into Unreal Engine I get grid pattern gaps all across the entire landscape. Any recommendations on how to fix?

![1](https://github.com/manticorp/unrealheightmap/assets/70861745/5953b185-9b67-4ef8-82f8-0322245f3a2d)
![2](https://github.com/manticorp/unrealheightmap/assets/70861745/e2943ea4-a098-471e-9095-c03919b27414)
![3](https://github.com/manticorp/unrealheightmap/assets/70861745/004f0907-78aa-42d2-9ba8-8029736e721b)

**Comment by manticorp** [comment]
That's very strange 🤔 can you share a screenshot of the import settings? And the URL which you downloaded the map with?

**Comment by dvogt2** [comment]
Here you go:
https://manticorp.github.io/unrealheightmap/#latitude/21.295772095071868/longitude/-157.68573760986328/zoom/14/outputzoom/15/width/2017/height/2017

![1](https://github.com/manticorp/unrealheightmap/assets/70861745/7b7c294c-a89c-4948-9f8f-fa1edf8c0109)

**Comment by manticorp** [comment]
Thanks for sharing - it looks like there is some noise and errors in the source data unfortunately - on first import into Unreal, this is the results I'm getting:

![image](https://github.com/manticorp/unrealheightmap/assets/3750419/b26c0573-5609-4bde-a6d7-3e536fe46943)

As you can see, it is very blocky and there are squares everywhere.

The only way to combat this is to manually clean the data in Photoshop, and with manual normalisation ranges.

You should also use the norm from 0 and norm to 675.883 for the normalisation of the output image:

![image](https://github.com/manticorp/unrealheightmap/assets/3750419/68c909ff-38bf-4207-b181-c575dbbe67fd)

And then use a z scaling of 132.01

![image](https://github.com/manticorp/unrealheightmap/assets/3750419/06e73722-a001-433f-a5bf-67fca5b884db)

After cleaning up the data in Photoshop, I get something like this:

![image](https://github.com/manticorp/unrealheightmap/assets/3750419/a9e1a3d1-aa3c-43c6-b708-36118282b405)

To easily achieve this, I exported the "Open Topo Map" albedo map, selected the blue water only, and then used that as a mask for the main image, making all the water black (i.e. height 0):

![image](https://github.com/manticorp/unrealheightmap/assets/3750419/0078b9a6-7f09-426d-9ec6-fe8f1166d591)

Hope this helps!

p.s. with a little bit of lighting and foliage:

![image](https://github.com/manticorp/unrealheightmap/assets/3750419/48ced6f6-f1e6-4573-ab48-164d4e458494)

**Comment by dvogt2** [comment]
Thank you so much for this explanation! If it isn't too much trouble for you, would you mind sending me a short video tutorial on how you did that in Photoshop? Ive been trying to figure out how to but i cant.

Happy New Years!
________________________________

**Comment by manticorp** [comment]
Sure! I won't do a video, but screenshots instead.

### Step 1: Generate heightmap and Albedo image and open both in Photoshop

![image](https://github.com/manticorp/unrealheightmap/assets/3750419/d75ad70a-5d57-4f9a-8b7d-bb0efcc384c3)

### Step 2: On the Albedo image, go to Select > Color Range

set fuzziness to 0 and click the blue water:

![image](https://github.com/manticorp/unrealheightmap/assets/3750419/7cc4d938-d80a-4d7c-b1a3-2ad14d0b7448)

### Step 3: Copy the water

ctrl + c to copy

### Step 4: Paste onto albedo image

![image](https://github.com/manticorp/unrealheightmap/assets/3750419/be6afa3c-678f-40e7-9a39-c45aceb168de)

### Step 5: Select the pixels of this new layer

You can ctrl + click on the layer thumbnail to select, or right click on the thumbnail and choose "Select Pixels"

![image](https://github.com/manticorp/unrealheightmap/assets/3750419/a4000eac-0219-4ee0-a6e2-8231ba231df2)

### Step 5: Create a new "Solid Color" black layer

With the previous selection active, it will create a masked layer of solid color.

![image](https://github.com/manticorp/unrealheightmap/assets/3750419/417be0f9-b00c-47b3-bcbb-3af34e9a721c)

### Step 6: Delete the previously pasted layer.

You should now have something like this:

![image](https://github.com/manticorp/unrealheightmap/assets/3750419/e68cc403-b70f-46b2-884f-08951db1b262)

### Step 7: Clean up further

There is still some artefacting in the image.

Using the brush tool you can edit the mask of the solid colour layer to get rid of the artefacts.

Before:

![image](https://github.com/manticorp/unrealheightmap/assets/3750419/d389d65d-a5ae-4c2f-91af-38f6cfaefba0)

After:

![image](https://github.com/manticorp/unrealheightmap/assets/3750419/55bac5ae-8bae-4663-946f-b65c51f238a0)

### Step 8: Clean up even more

There are other errors in this map - you can either clean these up in Photoshop or directly in Unreal Engine 

### Step 9: Save out

Finished!

![image](https://github.com/manticorp/unrealheightmap/assets/3750419/afd6d2d1-a653-484f-8730-15a0907a3352)

Make sure it is saved as a 16 bit grayscale PNG again!

**Comment by manticorp** [comment]
p.s. Closed because issue was in the source data, not the app - but glad I could help all the same :)

**Comment by dvogt2** [comment]
You are amazing! Thank you so much for this step by step instructions. The only issue im having now is saving it as a 16 bit greyscale. Ive been messing with the setting and even though i have 16 bit greyscale selected, its saving it as a 32 bit. Could you please send screen shots on how to properly export as 16bit greyscale. I promise thats the last ill ask of you lol!

Seriouly, i appreciate you taking the time to explain this to me!

________________________________

**Comment by manticorp** [comment]
Sure thing!

Make sure the image mode is set to Grayscale and 16 bits/channel:

![image](https://github.com/manticorp/unrealheightmap/assets/3750419/bd996197-2b92-48e5-bc7c-35408ae26c8a)

This is how it should be when opening the file as downloaded by the website. The info panel in photoshop should show untagged 16bpc:

![image](https://github.com/manticorp/unrealheightmap/assets/3750419/9a43764c-ca54-4dc0-acec-4e726201d649)

And then save the file as a PNG.

Best bet is to go to File > Save a copy:

![image](https://github.com/manticorp/unrealheightmap/assets/3750419/cbb624fa-636b-4c95-a874-011d98132da7)

Then it should save as a 16bpp png file 😁💪

The 16 bit thing gives you the greatest fidelity in terms if the heightmap, and is quite important, otherwise you'll get lots of stair-stepping when importing into Unreal Engine
