### ISSUE TITLE
Albedo Wont Generate

### ISSUE THREAD

**Issue by Heightmap** [manticorp/unrealheightmap#16]
hello manticorp, i found your web yesterday and it worked beautifully. today i was exploring your website and i found more options to view the map. i say that to say i dont know what i pressed because now i am unable to download the albedo map no matter on what map view i have it in. when i try to download i get an error that reads Faild to load image at tile x=0y=0-please try again.

**Comment by manticorp** [comment]
Hmm, I've tried a few places and it's definitely working for me!

Are you able to provide a URL where you cannot generate the albedo map? And a screenshot please?
