### ISSUE TITLE
Water higher than shore

### ISSUE THREAD

**Issue by NedRuss** [manticorp/unrealheightmap#18]
Aloha!

I love your heightmap product. It is fast and easy to use. It offers much more than other height map generators & even gives x, y, & z plane ratios. It's awesome.

My issue is that I'm trying to create a heightmap for Pearl Harbor. The problem is that the water shading is brighter than the shoreline around Ford Island, making the water in the harbor higher than the island itself. I included a picture below. Here is the URL - https://manticorp.github.io/unrealheightmap/index.html#latitude/21.36229206361992/longitude/-157.9607391357422/zoom/14/outputzoom/13/width/200/height/200

Ford Island is in the middle. The surrounding water is a bright gray, brighter than the edge of the island. This makes the water taller than the edge of the island in UE5. If it were a small area, I would carve it out. But there's a lot of water in Hawaii. My guess is that there is a setting I could adjust. This image uses default values. The altitude is -6m to 20m.

![21_362_-157_961_13_200_200](https://github.com/user-attachments/assets/3da91ec8-26b1-4a02-b34d-e458c00d9215)

<img width="443" alt="image" src="https://github.com/user-attachments/assets/fb328dce-6ecb-46c6-a1f8-0b3ab28196df">

Thanks in advance for any help.

**Comment by manticorp** [comment]
Hi, sorry for taking so long to reply!

This is unfortunately an issue with the base maps - nothing I can do about it. It looks like there are a lot of artefacts and whatnot around that area.

My only suggestion would be to use something like Photoshop to cut out the islands and make the water uniform.

One trick to do this quickly would be to use an albedo map to select the water 😉

Something like so (but with the water at the correct height I guess!):

![21_362_-157_961_14_505_505](https://github.com/user-attachments/assets/3654a25e-86ed-4f87-b648-e107c9645ee0)
