### ISSUE TITLE
Sculpt Erase Tool

### ISSUE THREAD

**Issue by Mannot74** [manticorp/unrealheightmap#20]
![Capture](https://github.com/user-attachments/assets/d226be0c-d144-4f13-b0d6-0cb3c0096203)

![Capture2](https://github.com/user-attachments/assets/f21e628c-f4f1-4b53-8883-7ac99036d19b)

Hello !

I imported a heightmap on unreal engine 5.4.4 from your online tool.

my "erase" tool in "sculpt" erases material when I am above half the height of the landscape, and adds material when I am below half the height of the landscape.

This only happens when I import a heightmap from your beautiful tool.

On the screenshots, we can see the vertical level where the erase tool "erases" and/or "adds".
We can also see a "grid" which is exactly at this vertical level.

**Comment by manticorp** [comment]
I believe this is the correct functionality - erase will set the level back to 0, setting anything below up and anything above down.

Erasing does not just get rid of stuff, if sets it to the default layer height (0).

You might need to move your landscape up/down on import, so that the bottom of the map is at 0 instead of whererever it is, if that's how you want it to work.

As this isn't an issue with the heightmap generator, I will close this issue - however, if you have more questions feel free to ask.

**Comment by Mannot74** [comment]
Thank you for your answer.
I understood after that the "erase" tool erased the modifications above or below a certain vertical level.

I changed the veritcal value before import and after import so that the lowest of the heightmap (landscape) is at the level (0 or 100 because originally it is the value 100 and it is at this value that the "erase" tool goes from deletion to addition).

But no matter the vertical value (-20000 -100 /0/ 100 25000 etc etc)
The landscape moves well, but the "0" point of the "erase" tool does not change, it is always at the same height of the heightmap (not of the world/environment, but of the heightmap and therefore of the landscape itself)

I controlled the vertical value by placing static meshes, one at the lowest point of the map, one at the place where the "erase" tool stops adding and starts removing.
and a last static mesh at the highest point of the map.

the total vertical height of my landscape is +/- 50,000 (-25000 /0/ +25000), and we realize that the "0" point of the "erase" tool is approximately in the center of the total height (the vertical middle).
and this regardless of the vertical values ​​of the landscape location.

Finally, I'm bothering you with this, because at the moment, all the parts/zones of the map being below the vertical middle of the landscape (70% of my landscape being lower than the vertical middle of the map), the "erase" tool will act as an "adder".

And if I add material to the landscape with the "sculpt" tool (at an altitude lower than the vertical middle of the lanscape) then I can't use the "erase" tool because it "adds" and I have to use the shift+sculpt combination to "dig" which is not what we want.

Can you tell me if you understand the problem?

**Comment by manticorp** [comment]
Hey,

I understand the issue...but I think this might still just be related to how UE5 stores landscapes.

To store the height, UE5 uses a 16 bit precision float from -256 to +255.992 (see [here under "Calculating Heightmap Z Scale"](https://dev.epicgames.com/documentation/en-us/unreal-engine/landscape-technical-guide-in-unreal-engine)).

I imagine to store that height range at your z-scale and precision, the 0 point _has_ to be in the centre of the z-height if your landscape file is going from pure black to pure white.

If you would like everything on your map to be above 0, then perhaps a heightmap starting at mid grey level would suffice? Or if you plan to go above/below the maximum extents, compressing the range down into a smaller range.

This could be accomplished using the levels tool in Photoshop, for example, by setting the left, black handle to mid grey.

I don't use Unreal Engine so I'm not sure on the technicalities of it, but this sounds like a limitation of Unreal Engine.

You could probably test this by creating a dummy landscape file, just a gradient from 0 black to 2^16 white and importing that, and seeing if you get the same issue.
