### ISSUE TITLE
[Request/Feedback] Decouple Area Selection Size (Rectangle) from Output Zoom

### ISSUE THREAD

**Issue by TheBango** [manticorp/unrealheightmap#6]
First of all, I just discovered your heightmap generator today and it's freaking awesome!

ATM the size of the selected area seems to be attached to the output zoom level and if the output zoom level is set to 13, then the selected area is smaller as with zoom level set to 14 and so on. So if I want a bigger area I'll have to deal with less detail.

My question is:
Is it possible to decouple the area selection size from the output zoom level, so that I can select a bigger area without losing details from the selected output zoom level?
Maybe it would make more sense if the size of the area would be based on the selected zoom level for preview.
This would help at least getting more information/details from the albedo map.

Another thing I'm wondering about is, why the size of the rectangle changes unproportionally with every output zoom level from 14 and below.
Is this a bug or to be intended?

**Comment by manticorp** [comment]
Hi! Glad you like the tool 😁👌

> ATM the size of the selected area seems to be attached to the output zoom level and if the output zoom level is set to 13, then the selected area is smaller as with zoom level set to 14 and so on. So if I want a bigger area I'll have to deal with less detail.

There are two variables that control the size of the exported area

* the zoom level
* the pixel size

The maximum zoom is 15 (which is the maximum zoom of the source data), but there is no limit on the pixel size except what your computer can handle.

> Is it possible to decouple the area selection size from the output zoom level, so that I can select a bigger area without losing details from the selected output zoom level?

Yes. If you want a higher detail for the same area, you can go up a zoom level, but then increase the pixel size as well. It is a log ratio, so going up 1 zoom level you will have to double the pixel size.

For example, if you are on 1000 x 1000px at zoom level 10, you can go to zoom level 11 to increase the detail, and increase the dimensions to 2000 x 2000px. This will represent the same area, but with twice the detail.

Does that make sense? Does that answer your question? The exported tiles are just based on mapping tiles, which have a set pixel resolution - so to export a bigger area for a given detail level, you have to increase the pixel size.

> Another thing I'm wondering about is, why the size of the rectangle changes unproportionally with every output zoom level from 14 and below.
> Is this a bug or to be intended?

I'm not sure what you mean? For me it is always square:

![image](https://user-images.githubusercontent.com/3750419/233481354-4d7ca66b-5703-4772-a749-d45512434e46.png)

![image](https://user-images.githubusercontent.com/3750419/233481408-c49d7669-2cc0-4546-a1a1-8beed02c9aec.png)

Are you able to post a screenshot?

**Comment by TheBango** [comment]
Hi 👋😃

Thanks for your reply!

> Does that make sense? Does that answer your question? The exported tiles are just based on mapping tiles, which have a set pixel resolution - so to export a bigger area for a given detail level, you have to increase the pixel size.

Ah true, I didn't knew that this is possible 😅🙈
Thanks for the hint! 

> I'm not sure what you mean? For me it is always square:

You should already see it in your pics, just look at the dimensions of the selected area. 
The dimensions in the first pic are 86,5 x 88,6 km with output zoom level set to 10. That's not a perfect square 😉 and probably leads into incorrect sizes/proportions within UE.
Regardless of the output pixel size, the higher the output zoom level, the greater the difference in the dimensions of the selection, except for output zoom level 15 and 14.

Here an example...
With output pixel size set to 8129 you'll get following dimensions per output zoom level:
24.8 x 24.8 km @ 15
49.4 x 49.6 km @ 14
98.4 x 99.3 km @ 13
195 x 199 km @ 12
382 x 397 km @ 11
735 x 795 km @ 10
etc.

Do you now understand what I mean?

Another thing I've noticed is that the marker doesn't stay on the selected location when zooming in or out. When zooming, the marker moves and the coordinates change.

**Comment by TheBango** [comment]
And another thing...
I saved the coordinates and then tried to paste them manually at lower zoom level, so the selected location keeps staying in the center, but it doesn't seem to work. As soon as I type in the latitude coordinate, the longitude coordinate also changes and vice versa.

**Comment by TheBango** [comment]
> Regardless of the output pixel size, the higher the output zoom level, the greater the difference in the dimensions of the selection...

I guess that this is also the reason why a horizontal black line appears at the bottom of the heightmap, as you can see in the following image

![heightmap_issue](https://user-images.githubusercontent.com/37959818/233648328-d64845ee-ae47-4e01-8440-39e68a924130.png)

**Comment by TheBango** [comment]
Sorry, for the spamming, but I ran into another issue 🙈

So I've set the output pixel size to 16258 to get a selection of 49.4 x 49.6km - 3.05m/px resolution at output zoom level 15. I was able to download the heightmap, but as soon as try to generate an albedo map based on the Open Street Map data, the download stops at 63/4160.

**Comment by TheBango** [comment]
Have I upset you or are you just too busy atm?

**Comment by manticorp** [comment]
> Have I upset you or are you just too busy atm?

Hi sorry I have been very ill the past few weeks, and I might not have time to look at these things for a while I'm afraid

**Comment by TheBango** [comment]
Hi, thanks for your reply!

> Hi sorry I have been very ill the past few weeks, and I might not have time to look at these things for a while I'm afraid

Oh, I'm sorry to read that and hope you'll recover soon!

> Aha, right I see what you mean. I think this is just slight areas in how this specific map projection works. To note, you will always get "errors" at large enough scales because of how you're trying to map the spherical world onto a square.
> 
> The widths will always be a little bit skewed, but to represent the mapping data 1:1 (the whole point of this repo) this is an acceptable sacrifice.
> 
> Another way to demonstrate this issue by moving your cursor at a fixed zoom from the equator to the poles - the square will start representing a smaller area (i.e. the mercator projection is artificially inflating those values).
> 
> Does this make sense?
> 
> **I.e. this is not a bug in the applcation, but rather a limitation of mapping the spherical planet onto a plane**
> 
> If you wish to more accurately model large sections of the planet, then this tool is not for you.
> 
> If you're happy with the slight mercator skewing (which shouldn't degrade the source data) then you will have to accept the slight measurement error.
> 
> Using you're examples, at zoom 13, the error is 4/199 = ~2%.

Well, it probably makes sense but I only do understand a bit as I don't know much about this subject matter 😅
However, I do understand if you can't submit any improvements in this case. 

> Is this when zooming with the mouse? That is intentional, it will zoom into the mouse location. If you would like to stay on the same point, you can change the zoom levels with manual zoom controls:

I've noticed that this also happens if I try to zoom with the arrows in the zoom panel. This is just my opinion but I guess that it would be more user friendly if setting/changing the location would be bounded to a press/click of LMB.

> I'm not sure what this black line is - are you able to provide a link and/or screenshot to the location? I will try to recreate the issue.
> 
> Can I also ask what browser / OS you're using?

Do you mean a link/screenshot of the location from your heightmap generator?
I use the latest versions of Chrome and Windows 11

> It may require trying multiple times to make this work. The rate at which we poll for tiles can stress some servers out, best bet is to refresh and try again :)

I already tried it several times but without success and finally I gave up 🙈

I really appreciate your help and in return for this I will gladly help you with feedback and suggestions 😊

**Comment by manticorp** [comment]
> Well, it probably makes sense but I only do understand a bit as I don't know much about this subject matter 😅
> However, I do understand if you can't submit any improvements in this case.

I think we've got to the bottom of this issue now, any more issues, can you please post them as a seperate issue? e.g. the zooming problem.

Thank you!

**Comment by TheBango** [comment]
Hmkay, I'll give it a try even if this means more work as I've to rewrite everything again
