### ISSUE TITLE
Confusing area size selection

### ISSUE THREAD

**Issue by TheBango** [manticorp/unrealheightmap#9]
The desired area size currently is attached to the set values in Output Zoom, Output Width and Output Height.
Changing one of those values also changes the area size accordingly.
This is somehow confusing and could be improved to be more user-friendly.

Output Width and Output Height also define the picture resolution which is fine.

Solution:
- Let the user set the area size in a separate box called e.g. "Area Size". The area size then shouldn't change until the user sets another value for this within this box.
- As Output Width and Output Height define the picture resolution, they could be merged to one box called "Output Resolution".
- Setting the Output Zoom Level only should define the maximum possible quality based on the set Output Resolution.

**Comment by manticorp** [comment]
> * Let the user set the area size in a separate box called e.g. "Area Size". The area size then shouldn't change until the user sets another value for this within this box.
> * As Output Width and Output Height define the picture resolution, they could be merged to one box called "Output Resolution".

This solution wouldn't allow for non-square outputs, e.g:

![image](https://github.com/manticorp/unrealheightmap/assets/3750419/583c1b55-5fe2-4e54-81cf-036b44a45dc2)

> * Setting the Output Zoom Level only should define the maximum possible quality based on the set Output Resolution.

Mm, I think you're right.

The more intuitive way of doing this would be to "click and drag" an area on the map, and then define the pixel dimensions you want for the file.

*However* this is a problem in this case, becase we can only allow certain fixed "zoom" or "resolution" levels (1), so we can't do any arbitrary dimensions & physical size combination.

In addition, for Unreal Engine & Unity (& possibly other softwares) they will only allow certain pixel dimensions.

Hence...I think the current solution is still the best for the moment, if a little unintuitive.

If you can think of a way that satisfies the above constraints, feel free to re-open the ticket!

(1) : The data is only provided at fixed resolution levels, and interpolating between any of these levels (i.e. allowing arbitrary size & zoom level combos) would severely limit the resolution, and be no better than most existing tools.

**Comment by TheBango** [comment]
> This solution wouldn't allow for non-square outputs, e.g:

Okay, if you want the user to be able to also get a rectangle selection then probably adding two input fields - one for each axis - would be a better solution. 

> The more intuitive way of doing this would be to "click and drag" an area on the map, and then define the pixel dimensions you want for the file.

No, I don't think so. Let me try to explain it by the following example:
Let's say the user wants to create a box selection of 16 km² - square selection would be 4x4 m and a rectangle selection 2x8 m.
Now he has to create a box by click and drag (freehanded I guess), but he doesn't get the correct size. Even after several tries he still doesn't get a selection of 16 km². 
However, it could work if you would add this way of area selection as an option, so in addition the user can then also adjust the selected area by typing in the values for each axis manually.

**Comment by manticorp** [comment]
Ah right - I see what you mean, so I guess you're asking for selection by physical measurements instead of pixels?

The thing that stopped me from doing this is that the calculations are quite difficult! It is definitely something that could be implemented, though.

Perhaps a toggle, for example to switch from pixel beased measurements to physical measurements?:

![image](https://github.com/manticorp/unrealheightmap/assets/3750419/ca17edb5-6b3c-4fbc-a8e1-83f7b1cc94ce)

**Comment by TheBango** [comment]
I don't think that this solves the actual problem. The main problem is that changing the Output Zoom Level also changes the size of the selection and that shouldn't happen in my opinion. Therefore I thought that separating the individual inputs (Output Zoom Level, Output Image Resolution and Area Size) from each other would make more sense and offers more possibilities.

Let me try to explain what I mean with another example:

Let's say you want to select an area of 16 km² with an image size/quality of 8129 x 8129 px and the Output Zoom Level set to 15 or higher. This currently isn't possible because a) you can't set the area size specifically and b) changes in both, the image size (Output Width/Height) and the Output Zoom Level, do change the area size independently.
This makes it hard to get the expected result.
In this case I think we should be able to set and change the area size only by defining it in a separate input field called Area Size and changes in the other two input fields shouldn't affect the area size.

I hope you now understand what I mean.
